package com.tutorial.events.models;

import java.sql.Timestamp;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@RequiredArgsConstructor
public class Events {
    private final String url;
    private final String payload;
    private final String referenceId;
    private final int maxRetries;
    private Timestamp createdAt;
    private Timestamp completedAt;
    private boolean isCompleted;
    private boolean isFailed;
    private String exceptionMessage;
}


/**
 *  url: `https://example.com/create-example` //,
    payload: json, //payload to be consumed by the event
    eventId: binary //generated by api, used to identify an event.
    referenceId: binary, // a unique id used to group events together.
    maxRetries: integer //maximum number of retries an event worker should attempt before moving to the next task.
    createdAt: timestamp, //generated by api, used to show when an event was created.
    completedAt: timestamp, //generated by api, used to show when an event was completed
    isCompleted: boolean //generated by api, used to show if an event is completed.
    isFailed: boolean //generated by api, used to show if an event failed.
    exceptionMessage: json || string, //the failure response of the endpoint if an event fails, 
 */